walker:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  
  # HIPS
  left_hip_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_hip_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}

  right_hip_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_hip_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}

  # CARRIAGES
  left_carriage_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_carriage_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}

  right_carriage_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_carriage_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}

  # LEGS
  left_leg_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_leg_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}

  right_leg_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_leg_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}
